---
version: "3"

services:
  openvpn-client:
    image: d3vilh/openvpn-client:arm64v8
    container_name: openvpn-client
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - ALLOWED_SUBNETS=192.168.88.0/24
    volumes:
      - ./client:/config
    restart: unless-stopped
